### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by peterneher** [demianw/tract_querier#32]
Hi everyone,

I was just trying to install tract_querier and got the following error after running "python setup.py install":

```
Installed /home/neher/.local/lib/python2.7/site-packages/tract_querier-0.1-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    **(configuration().todict())
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/neher/.local/lib/python2.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/neher/.local/lib/python2.7/site-packages/setuptools/command/install.py", line 97, in do_egg_install
    cmd.run()
  File "/home/neher/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 358, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/neher/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 574, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/neher/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/neher/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)
```

Any suggestions what might cause this?

Cheers,
Peter

**Comment by demianw** [comment]
Hi!

Could you also report the version of `distutils` installed in your system for better debugging?

**Comment by peterneher** [comment]
distutils is version 2.7.12

**Comment by demianw** [comment]
Dear @peterneher I have not been able to reproduce this bug. However, I pushed some minor changes to the tool. Would you mind verifying if it works now?

**Comment by peterneher** [comment]
Unfortunately it still doesn't work. But I will let you know if I figure it out.

**Comment by demianw** [comment]
Weird,

Could you start a virtual environment (with venv) and try installing it there?

**Comment by peterneher** [comment]
Hi Demian, sorry for the late reply. I didn't try it but my colleague @wasserth did. It works fine in a virtualenv but on his normal linux he encountered the same issue. 
Maybe it's actually possible to ignore it. But when I encountered the following isse with my faulty installiation, I thought it might be caused by the installation problems: https://github.com/demianw/tract_querier/issues/33
Turns out that this is not the case.

**Comment by demianw** [comment]
Hm, weird. I tried installing it in different linux boxes and it worked. Maybe it is a problem of a tune-up that your linux distro has? I tried to install this on my Apple computer on the system python distribution at in t worked.

Could you please specify the linux distribution you are using?

**Comment by peterneher** [comment]
I'm using ubuntu 16.04

**Comment by demianw** [comment]
OK, I will try to check the linux distribution in ubuntu. However different continuous integration frameworks work well so it might be a specific problem with ubuntu. I'd recommend to use miniconda or anaconda as a main python installation.

**Comment by demianw** [comment]
@peterneher The last updates should fix the bug. Could you please verify if this works now?

**Comment by peterneher** [comment]
@demianw Everything works like a charm now!

**Comment by demianw** [comment]
Great!
